# Generated by Django 4.0.6 on 2022-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='artigo',
            field=models.TextField(default=''),
        ),
    ]
